// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7lODV7Uueg-geltz0w36jCnef2xJDHqc',
    appId: '1:832149351276:web:827501a2ca77067b1f2149',
    messagingSenderId: '832149351276',
    projectId: 'login-with-firebase-88b7a',
    authDomain: 'login-with-firebase-88b7a.firebaseapp.com',
    storageBucket: 'login-with-firebase-88b7a.appspot.com',
    measurementId: 'G-PCND14RS44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8dWsJNiQZRBzrXfhr6tt43JemHGuiS84',
    appId: '1:832149351276:android:2cc86b0c6ef348181f2149',
    messagingSenderId: '832149351276',
    projectId: 'login-with-firebase-88b7a',
    storageBucket: 'login-with-firebase-88b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJR1SgGNdDebc1fb0zFVmAKiVdUCfQ__Q',
    appId: '1:832149351276:ios:9e1b79ef1b8b616f1f2149',
    messagingSenderId: '832149351276',
    projectId: 'login-with-firebase-88b7a',
    storageBucket: 'login-with-firebase-88b7a.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJR1SgGNdDebc1fb0zFVmAKiVdUCfQ__Q',
    appId: '1:832149351276:ios:d9011403a0d848ee1f2149',
    messagingSenderId: '832149351276',
    projectId: 'login-with-firebase-88b7a',
    storageBucket: 'login-with-firebase-88b7a.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
